### ISSUE TITLE
CI test with V8 when on Dockerhub

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-virtual-schema-lua#31]
## Situation

Tests with a development version of V8 are only available locally. Currently, the CI tests run with 7.1.18 and skip remote tests.
Once V8 is on Dockerhub, we need to reenable CI tests with V8 in `ExasolVritualSchemaTestConstants`.

## Acceptance Criteria

* CI tests run with Exasol version that supports remote login via Lua.

**Comment by redcatbear** [comment]
Blocked by missing `docker-db` 8.x.x on Dockerhub: https://hub.docker.com/r/exasol/docker-db/tags

**Comment by ckunki** [comment]
8.18.1 is available on dockerhub, but using the old flavor without C4.
