### ISSUE TITLE
TLS Certificate Validation

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-virtual-schema-lua#36]
## Situation

In #23 we realized that TLS certificate validation is not yet possible in Lua, because Lua has no file system access and thus cannot read from the certificate store.

Since this requires a database change, we decided to create this follow-up ticket of #23 to add certificate validation support once the database is prepared for this.

## Acceptance Criteria

- An integration test proves that a TLS connection requires a valid peer certificate in order to establish a connection.
- Event-driven way to find out when to restart the database after installing a certificate (`install_test_certificate.sh`).

**Comment by ckunki** [comment]
Currently no progress.
